apiVersion: v1
entries:
  configserver:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
        - kind: added
          description: Added the changelog
      artifacthub.io/images: |
        - name: configserver
          image: 2martens/configserver:latest
          platforms:
            - linux/amd64
            - linux/arm64
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-08-21T20:22:59.785749795Z"
    dependencies:
    - name: template
      repository: https://repo.2martens.de/charts
      version: 0.1.9
    description: Minimal Spring Boot config server
    digest: 31604439528631ddafd751a64836d5fcd88e172b204e10e997aa873276512f77
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: configserver
    sources:
    - https://git.2martens.de/2martens/config-server
    type: application
    urls:
    - https://repo.2martens.de/charts/configserver-0.1.5.tgz
    version: 0.1.5
  template:
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Added annotation to mark this as a pre-release
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-08-21T20:22:59.786835243Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 748418826f8626c4c5fbfae5c547bbc6170667b0e739a2161b83e709fc61b863
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.10.tgz
    version: 0.1.10
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
        - kind: fixed
          description: Fixed annotation of the changes so they actually appear
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-08-21T20:22:59.793071408Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 454a42f431ff34b1fcd234cf3ee247125d3f844f5c058834625e02da02660534
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.9.tgz
    version: 0.1.9
  - annotations:
      artifact.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-08-21T20:22:59.791095674Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 9a8c2d6325e825b50bc03bce5371c37d3c31e679e172bb7ae1dcac5f08e52aea
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    created: "2023-08-21T20:22:59.789289341Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 191ee5b13b058684e8caaa6fc7ddc347136a087a79f9584a9d91246505c2ff1f
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    created: "2023-08-21T20:22:59.787108285Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: be14de9bb789ee27782a8b13db03444e0c09344c63a3065769f76bdf75daec6f
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.6.tgz
    version: 0.1.6
generated: "2023-08-21T20:22:59.783651579Z"
