apiVersion: v1
entries:
  configserver:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Updated image tag
      artifacthub.io/images: |
        - name: 2martens/configserver:0.1.17
          image: 2martens/configserver:0.1.17
          platforms:
            - linux/amd64
            - linux/arm64
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.694810092Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.14
    description: Minimal Spring Boot config server
    digest: fd7dadeba4b4c0f02169e4182881a8c2ceca046b34ea13d0aa257505a9d8c1a2
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: configserver
    sources:
    - https://git.2martens.de/2martens/config-server
    type: application
    urls:
    - https://repo.2martens.de/charts/configserver-0.1.17.tgz
    version: 0.1.17
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Changed imaged name in annotations to show repository
      artifacthub.io/images: |
        - name: 2martens/configserver:latest
          image: 2martens/configserver:latest
          platforms:
            - linux/amd64
            - linux/arm64
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.700270477Z"
    dependencies:
    - name: template
      repository: https://repo.2martens.de/charts
      version: 0.1.9
    description: Minimal Spring Boot config server
    digest: d31d6ca701a6f0e3799fc50e079f6dd434e2454d57960f9ab3dc1a13bc4210c8
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: configserver
    sources:
    - https://git.2martens.de/2martens/config-server
    type: application
    urls:
    - https://repo.2martens.de/charts/configserver-0.1.7.tgz
    version: 0.1.7
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Added missing prerelease annotation
      artifacthub.io/images: |
        - name: configserver
          image: 2martens/configserver:latest
          platforms:
            - linux/amd64
            - linux/arm64
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.698599617Z"
    dependencies:
    - name: template
      repository: https://repo.2martens.de/charts
      version: 0.1.9
    description: Minimal Spring Boot config server
    digest: 65b25cd3a29de27348c8c880b554badf3fb075529ed9f9cfbfe7e72005e081d9
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: configserver
    sources:
    - https://git.2martens.de/2martens/config-server
    type: application
    urls:
    - https://repo.2martens.de/charts/configserver-0.1.6.tgz
    version: 0.1.6
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
        - kind: added
          description: Added the changelog
      artifacthub.io/images: |
        - name: configserver
          image: 2martens/configserver:latest
          platforms:
            - linux/amd64
            - linux/arm64
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.697010118Z"
    dependencies:
    - name: template
      repository: https://repo.2martens.de/charts
      version: 0.1.9
    description: Minimal Spring Boot config server
    digest: 31604439528631ddafd751a64836d5fcd88e172b204e10e997aa873276512f77
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: configserver
    sources:
    - https://git.2martens.de/2martens/config-server
    type: application
    urls:
    - https://repo.2martens.de/charts/configserver-0.1.5.tgz
    version: 0.1.5
  kafka:
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Fixed version and values
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.703347713Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.14
    description: Simple Kafka chart to get started
    digest: d9bb152422cce6162493ef0654d137b144fb1ac7221634e3699b34596d697322
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: kafka
    type: application
    urls:
    - https://repo.2martens.de/charts/kafka-0.1.4.tgz
    version: 0.1.4
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Added Artifact metadata
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.701818895Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.14
    description: Simple Kafka chart to get started
    digest: 1d0052f172fdd8605dba75b2053239a9a01de62691b376514f877723c7f88a30
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: kafka
    type: application
    urls:
    - https://repo.2martens.de/charts/kafka-0.1.3.tgz
    version: 0.1.3
  template:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Added more configuration options for applications
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.706760794Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 24698e9ca2457c65e9d663572a1486a0a19020ece1b1c6752d2f66ef8f755b4e
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.14.tgz
    version: 0.1.14
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Fixed secret and ingress files
        - kind: added
          description: Added support for ArgoCD application configuration
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.705813942Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 6fcb903af84d7eb5bc4b740cdce4d771d2be9fbc4c94b34edd4339403e382055
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.13.tgz
    version: 0.1.13
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Added annotation to mark this as a pre-release
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.704139843Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 748418826f8626c4c5fbfae5c547bbc6170667b0e739a2161b83e709fc61b863
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.10.tgz
    version: 0.1.10
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
        - kind: fixed
          description: Fixed annotation of the changes so they actually appear
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.709486066Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 454a42f431ff34b1fcd234cf3ee247125d3f844f5c058834625e02da02660534
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.9.tgz
    version: 0.1.9
  - annotations:
      artifact.io/changes: |
        - kind: added
          description: Completed README to contain all steps required to jumpstart an application chart
        - kind: added
          description: Added sign key entry to make verifying easier
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.708734497Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 9a8c2d6325e825b50bc03bce5371c37d3c31e679e172bb7ae1dcac5f08e52aea
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    created: "2023-10-30T00:25:55.707836767Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: 191ee5b13b058684e8caaa6fc7ddc347136a087a79f9584a9d91246505c2ff1f
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    created: "2023-10-30T00:25:55.707004157Z"
    description: A Helm library chart containing common templates, keeping application
      templates short
    digest: be14de9bb789ee27782a8b13db03444e0c09344c63a3065769f76bdf75daec6f
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: template
    sources:
    - https://git.2martens.de/2martens/cloud-configuration
    type: library
    urls:
    - https://repo.2martens.de/charts/template-0.1.6.tgz
    version: 0.1.6
  wahlrecht:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Added additional ArgoCD configuration options
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.713255871Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.14
    description: Installs the Wahlrecht API into the Kubernetes cluster
    digest: 34cc4c6faba2fe7694b3ca979297798c536952d0cf939230a20f834541a15dcd
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: wahlrecht
    sources:
    - https://git.2martens.de/2martens/wahlrecht
    type: application
    urls:
    - https://repo.2martens.de/charts/wahlrecht-0.1.8.tgz
    version: 0.1.8
  - annotations:
      artifacthub.io/changes: |
        - kind: fixed
          description: Configured port and actuator port now match spring configured values
        - kind: added
          description: Added support for ArgoCD application configuration
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.711335728Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.13
    description: Installs the Wahlrecht API into the Kubernetes cluster
    digest: 310003c29cd5af198a2d295d36321ca0c6c6cfbfa3eb8153180d32d3f8d4f506
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: wahlrecht
    sources:
    - https://git.2martens.de/2martens/wahlrecht
    type: application
    urls:
    - https://repo.2martens.de/charts/wahlrecht-0.1.7.tgz
    version: 0.1.7
  zookeeper:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Added ArtifactHub metadata
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: F0F153B65BAD467201D7544E47393ABD1F96B7C8
        url: https://mafiasi.de/pks/key/47393ABD1F96B7C8.asc
    apiVersion: v2
    created: "2023-10-30T00:25:55.714704288Z"
    dependencies:
    - name: template
      repository: file://../template
      version: 0.1.14
    description: Simple Zookeeper chart to get started
    digest: 7d2f3d33cc41c5598bc1d3b86a713cd886514e9da501967e080332b1f273c79c
    maintainers:
    - name: Jim Martens
      url: https://2martens.de
    name: zookeeper
    type: application
    urls:
    - https://repo.2martens.de/charts/zookeeper-0.1.3.tgz
    version: 0.1.3
generated: "2023-10-30T00:25:55.690308838Z"
