name: Deploy index
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update index file
        run: ./scripts/generate-index.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'charts/index.yaml'
          message: '[GitHub Actions] Updated index.yaml [ci skip]'
          default_author: 'github_actions'
  deploy-repo:
    runs-on: ubuntu-latest
    needs: update-index
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare files
        run: |
          mkdir deploy
          cp -R .htaccess charts files deploy
      - name: Copy files to remote
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -az -r --del
          path: deploy/.
          remote_path: ~/tmp/build
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Activate new files
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            shopt -s dotglob
            rm -rf html/*
            cp -r tmp/build/* html/
            rm -rf tmp/build

